Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -17,29 +17,14 @@ jobs:
           paths:
             - ~/.m2
           key: 'CircleCI-App-{{ checksum "pom.xml" }}'
-    # Generate apk
-      - run: ./gradlew assembleDebug
-
-      # Upload app to BrowserStack and set app url in an environment variable.
-      # Here replace app-debug.apk with name of your apk.
-      - run:
-          name : App upload and Set app id in environment variable.
-          command : |
-            APP_UPLOAD_RESPONSE=$(curl -u "nithyamani3:P4JKysg5WuchQxBfKQu1" -X POST https://api-cloud.browserstack.com/app-automate/upload -F "file=@/Users/nithyamani/Desktop/APPS/WikipediaSample.apk")
-            APP_ID=$(echo $APP_UPLOAD_RESPONSE | jq -r ".app_url")
-            if [ $APP_ID != null ]; then
-              echo "Apk uploaded to BrowserStack with app id : ",$APP_ID;
-              echo "export BROWSERSTACK_APP_ID=$APP_ID" >> $BASH_ENV;
-              source $BASH_ENV;
-              echo "Setting value of BROWSERSTACK_APP_ID in environment variables to  ",$APP_ID;
-            else
-              UPLOAD_ERROR_MESSAGE=$(echo $APP_UPLOAD_RESPONSE | jq -r ".error")
-              echo "App upload failed, reason : ",$UPLOAD_ERROR_MESSAGE
-              exit 1;
-            fi
-
-      # run tests!
-      - run: ./gradlew test
+      -
+        run: './gradlew assembleDebug'
+      -
+        run:
+          name: 'App upload and Set app id in environment variable.'
+          command: "APP_UPLOAD_RESPONSE=$(curl -u \"nithyamani3:P4JKysg5WuchQxBfKQu1\" -X POST https://api-cloud.browserstack.com/app-automate/upload -F \"file=@/Users/nithyamani/Desktop/APPS/WikipediaSample.apk\")\nAPP_ID=$(echo $APP_UPLOAD_RESPONSE | jq -r \".app_url\")\nif [ $APP_ID != null ]; then\n  echo \"Apk uploaded to BrowserStack with app id : \",$APP_ID;\n  echo \"export BROWSERSTACK_APP_ID=$APP_ID\" >> $BASH_ENV;\n  source $BASH_ENV;\n  echo \"Setting value of BROWSERSTACK_APP_ID in environment variables to  \",$APP_ID;\nelse\n  UPLOAD_ERROR_MESSAGE=$(echo $APP_UPLOAD_RESPONSE | jq -r \".error\")\n  echo \"App upload failed, reason : \",$UPLOAD_ERROR_MESSAGE\n  exit 1;\nfi\n"
+      -
+        run: './gradlew test'
       -
         store_test_results:
           path: target/surefire-reports
